### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by NiceSapien** [salahawk/discord-bot-chatgpt#1]
Please send new link.

**Comment by salahawk** [comment]
https://discord.gg/nx2sbe98

**Comment by salahawk** [comment]
Feel free to contact me on Discord (salahawk#7119)

**Comment by salahawk** [comment]
The bot is down now (but am eager to restart once requested) due to OpenAI bill 😛

**Comment by NiceSapien** [comment]
Thanks
